ansible_user: "root"
ansible_port: 1337
exitnodes:
  # aegidientor: { id: 1, ip4: "{{ lookup('dig', 'aegidientor.e.ffh.zone./A') }}" }
  # steintor: { id: 2, ip4: "{{ lookup('dig', 'steintor.e.ffh.zone./A') }}" }
  leintor: { id: 3, ip4: "{{ lookup('dig', 'leintor.e.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'leintor.e.ffh.zone./AAAA') }}" }
  # clevertor: { id: 4, ip4: "{{ lookup('dig', 'clevertor.e.ffh.zone./A') }}" }
  # listertor: { id: 5, ip4: "{{ lookup('dig', 'listertor.e.ffh.zone./A') }}" }
  # bruehltor: { id: 6, ip4: "{{ lookup('dig', 'bruehltor.e.ffh.zone./A') }}" }
superexitnodes:
  sn01: { id: 1, ip4: "{{ lookup('dig', 'sn01.s.ffh.zone./A') }}" }
supernodes:
  sn01: { id: 1, ip4: "{{ lookup('dig', 'sn01.s.ffh.zone./A') }}" }
  # sn02: { id: 2, ip4: "{{ lookup('dig', 'sn02.s.ffh.zone./A') }}" }
  # sn03: { id: 3, ip4: "{{ lookup('dig', 'sn03.s.ffh.zone./A') }}" }
  # sn04: { id: 4, ip4: "{{ lookup('dig', 'sn04.s.ffh.zone./A') }}" }
  # sn05: { id: 5, ip4: "{{ lookup('dig', 'sn05.s.ffh.zone./A') }}" }
  # sn06: { id: 6, ip4: "{{ lookup('dig', 'sn06.s.ffh.zone./A') }}" }
  # sn07: { id: 7, ip4: "{{ lookup('dig', 'sn07.s.ffh.zone./A') }}" }
  sn08: { id: 8, ip4: "{{ lookup('dig', 'sn08.s.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'sn08.s.ffh.zone./AAAA') }}" }
  sn09: { id: 9, ip4: "{{ lookup('dig', 'sn09.s.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'sn09.s.ffh.zone./AAAA') }}" }
  sn10: { id: 10, ip4: "{{ lookup('dig', 'sn10.s.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'sn10.s.ffh.zone./AAAA') }}" }
helpernodes:
  harvester: { id: 1, ip4: "{{ lookup('dig', 'harvester.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'harvester.ffh.zone./AAAA') }}" }
  observer: { id: 2, ip4: "{{ lookup('dig', 'observer.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'observer.ffh.zone./AAAA') }}" }
  ns1: { id: 3, ip4: "{{ lookup('dig', 'ns1.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'ns1.ffh.zone./AAAA') }}" }
  web: { id: 4, ip4: "{{ lookup('dig', 'web.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'web.ffh.zone./AAAA') }}" }
  monitor: { id: 5, ip4: "{{ lookup('dig', 'monitor.ffh.zone./A') }}", ip6: "{{ lookup('dig', 'monitor.ffh.zone./AAAA') }}" }
simple_mail:
  root_email: monitoring@hannover.freifunk.net
  mail_server: mail.ffh.zone
git_addr: ssh://git@git.ffh.zone:1337
stats_pushgateway:
  host: "[fdca:ffee:8::108]:9091"
reboot_on_kernelpanic: true
journald_watch_enabled: true
journald_watch_mailto: "monitoring@hannover.freifunk.net"
journald_watch_filter_regexes:
- '/kernel: do_IRQ:.*No irq handler for vector \(irq -1\)/'
- '/sshd.*fatal: no matching cipher found/'
- '/sshd.*fatal: no hostkey alg \[preauth\]/'
- '/sshd.*fatal: Read from socket failed: Connection reset by peer \[preauth\]/'
- '/sshd.*fatal: Unable to negotiate a key exchange method \[preauth\]/'
- '/sshd.*error: Received disconnect from.*com.jcraft.jsch.JSchException: Auth fail \[preauth\]/'
- '/sshd.*error: Received disconnect from.*com.jcraft.jsch.JSchException: timeout in waiting for rekeying process. \[preauth\]/'
- '/sshd.*error: Received disconnect from.*Handshake failed \[preauth\]/'
- '/sshd.*error: Received disconnect from.*no authentication methods available \[preauth\]/'
- '/sshd.*error: Received disconnect from.*No supported authentication methods available \[preauth\]/'
- '/dhcpd.*parse_option_buffer: malformed option dhcp.*(code.*): option length exceeds option buffer length./'
- '/dhcpd.*Failed to send.*byte long packet over fallback interface./'
- '/dhcpd.*: send_packet: Operation not permitted/'
- '/dhcpd.*: icmp_echorequest .*: Operation not permitted/'
- '/dhcpd.*: uid lease .* for client .* is duplicate on/'
- '/dhcpd.*: client .* has duplicate leases on /'  # client requests a new (different) address/lease without releasing the old one
- '/dhcpd.*: Abandoning IP address 10.*: pinged before offer$/'
- '/dhcpd.*: Abandoning IP address 10.*: declined.$/'
- '/systemd[.*]: phpsessionclean.service: Failed at step NETWORK spawning.*Permission denied/'
- '/systemd[.*]: Failed to start Clean php session files./'
- '/fastd@mesh.*: .*dump status: write: Broken pipe/'
admin_pubkeys:
- name: lemoer
  key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK4qBzYhG0oXJCAVr5Bgh9dJ2ZqgzsB9oTGZlBn5ZIjO lemoer
- name: cawi
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkTAH3SP+jwPw4RFDKw5b4IYEc1wcEPvQ/NHXmaeEMyAo23U3VKB1Wpu2XKs06qstzFppGE5pKMW7mYu4sHGMhsJeG4m9cUHbq4Zg80K6CVxya49LvIeGaPZ5r6MrojUdpslVNcjLboN5cho5vfLO2yyyVlZYrwax4ZKvADHMoBBJX6qnmRYoATYRX24aEOLS274ogytm6P12WyBpqPdBWZnOvNJQPhgkCzIIVDguDAHvm8RKOEFl7g6MLAsco2OgXrD8GjT4QkaGBpHBSTxjzqZ40yX9UswDRQSnLjBQH5lx3QE+O9u/mbnkabYA2WOuqb2HIpFmpr/MbCHUbCRi75pa+abu+Hf5rQtLGanmsxeUwr30XaChWwGQBklJnWNkjdYiI7qPxo7zKl8lu+GE9F8P5CdvlsB48iygpJSWQe8dRxvu5cAjIo31mPlLhr6YkvCDcOYgkzRbgHjtvFknVj/13SI6XaKVIgQvVc/R3rR7T696xmn0usPORCZoxy5fkuDu3slSbwGOqqPWnET822U07osbcbhEq6OFdUV2NPfborQjdOJ3jwwO9NOsVCv0tLW12X0+FMX1AXI/KG6xwHtJlFgN9fuzDVn2PIsEB55NzxIRuvcyTBXHjqGiSkbwejZpBpPgz1FaqMWfsw6FqtJaWBEOLpXcpee1p/0CHjw== cawi
- name: manawyrm
  key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAhdgtEnpoaA6FLhAm0kDHH2NJEI0jqbkkL4wJz9rfDOdUN0/iBLxtk259KKKTPhdNah8UASjkVtqBypDzZeUUxrikW4WPDzaD+lyI8wWN3+c4hpUJGIyYnVkmjlB61IyqRWZGjbqBEzJvzTcih/VHQda5qNBrZ56E9oYy7BegHr64ZUl3hETSX3RHuNutF6YpuMsH0oNuf8uq3KQonKGSsAPkPzAphDOkUCxdS86WYR63xJEQySm5gFvakFUznweYKb71LAGTiIzmsO8I1IcEOc4K7vNQzmZFapo36BxbqP1K9eataXGm0ZzpzRQrKQjuwfOEKZ38j5k5MwrzdxdGk0UJGyBYZipFBX9hAwwRb5TBvtcDZPhooOgZNptGU2wBwS8ZmyUJ5F4LtIQOY0zulF+6y0BWd258Cf8A22nweRAi+ok0DUjp3P9YxoNV58eL4GjWVNjakhcy6IGhkevP309sGOJ9BT9m5TmYfhn5ftenqNl5ZFkk41DHhDSry1hDFGSonSOIR+ogvzWwNdKw9vhfHtoFJt/k19elQfT1PC61g+xci8wRsCxUEaCcrAKUg57Nu51Dbkft7NjnwhahgPcq27tOBOhluDu6trJY7zFcwOGTYlqeP9BSEiqaRpZVLvUGQpyvfnLnNGrVPmkkPipdXdt+Ha2okUoNZZqtREM= manawyrm
- name: aiyion
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDgEfnFJstK12AIskz/oSciCfNstxRWl6Nucz/8gnUo9dIYOrznJsac01KNY7VpYJbrnc9VwbMl0j0y9aFVM8uoHNgyGZmO7bwazyT4ukobVEV7EHImizdlzf8YQF0eqlybAHH3JxhnljLGOmpJTLQAgC8NM5PLMZaOrcUHSDmy5Kavfu7fQEdmVst9xD0LS8D9CXR0ZqyvfFq0f7HfDnWJI7NLtknSr4ensaOBUHsZRkU2bvQZY5hyz0OM+w06AlXJ/6hQe4V6EiEpQOxqyev+1gyr2KBX9JMNyzrNXCxYysiebniMFBcWzkT8F+S0V2B8axkE1ZQ24Mp6KGfnB/qU1wVFFrOEw6OiAPBRv6+KzTsGgXrgCAQZRg6Du7JQNbxrW0sPvRiqYQRQRH/GHFFr/DOs/PBUzcJgnV80PmJGTLWnAg+kd+FBODJWZ+ow9be1248IsEElacolpCGBZRdvicVsNelKMZ6385ZvkhOZZxNwYCQq7O2sAQ6pWrBF4x431x4jDqVDHkcN/5EYi0nkQ5zPt5J9Ola5zCjWgQD0sjUi+aZc0WyVYU4jcy6y4V/VET3fvop1ptr6Q8VAEqkmw1UDOCxTqN+48N90XL3mHXJDTgPfkf20jBOv3+RjEhks+Jrf/LCrHV2MXViuFA0r2gDlP4gfC9Sh9xEWRqA0fQ== aiyion
- name: jue
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRjccH1Tx2UKKSs4Q4GXvq4oV4oT3BGVe5SUHWWa7pVTI8qeii1si3ZlfyZi6r8R3djfz9X/Kvgp/GJL6pH7fSofUU0F4Asb9UmwtY7/34nLXU9HYmdIVVX0to1KubMcJxjoBM2Z+IyNlmkCZpRN+Ztfh+vW+05w5nTTgITfutC18PYkgIIkFJL+SY5UjAY85vy4WmVL7EnQSy3pevBOXLr9ksZQ6N1uC7jSPOgaOQv8IUzFBvdtMZNUu0tXnZiC4w/FShrOTC8XeU0dSWoQQsJXJrdTy6R7gGnR6leQG1uwDsDmEPYOT21JbqurOSqPRQ1coZBjPm5EvhjCRTdqnN jue
- name: okrueger
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTK3tHtQ0Vo2VKOGKOirtbg1hUI/E4kUl9jQIaelHtkZGFSkQr5EewEv2lUflF9JyFtpqz8HO8dBzvQtyXFC0XU1RKnHBwj2OKVc8/le0fSDaMeCHkIhtSolsCfUZJ49iEDMRtOkXimDYR95KsHWvy0I/T1oyOu0NhgNXcrmQuoEWLiVImU0LVxnzGImAKezylrlNNUM9bfYk6HNH17tSttyA4a31HYSHvCxnd567UWjhsewgQgnzsAOnIvJYCekFFIdmQVmEC7Kg1ubNzydd9YkKJvSNQb8Hfx2csZ0FRyk1v2YTIKFZlxbK14I7BrRp9pSH91SYHPBLKCj5Jun0JROE67KlQGevyO9bWBvjwfzTZpmI1KG4eHNxc7KWgdIX5O4kDANIst7KZy7qVvJOuKzWhRkR5yYneqUESB4GS3m4eDXY8RHE1mkSH1lmuMcspFvHPrJUc8LI9f3MrB4X0rNEw2GOnUZ+q4KGUcNxu0zd/gkRu4yCzH511qdXc3DUZgatt2vDmY8MMd1QYscaAL/noVNxIX4hZU/BubJYyFdgeDk4TyVdrBZ1HxuBvYg5ZTa6zB9aj/+HCuby4YyXT7vu5f7fx5R/8aj9kyLS3wKM+7yPAIRJb+p5iPxpeqtQ9BtgdMAJ2mV15dxlclDdk7cs3nPfoqbiae4esxXh0Bw== 1977er
- name: raute
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUTWi7wjQ1lHwKee8oB4JAbpgJNRC4+7eIrEXT+e7ifCh45/fSDun+OCQKM69AV4C/CS612QAQ0SkRql3R54N0ChRfD7Pyr/JQl2ufD0TcXt8wby1CeFJRSSPjd31E7+hDyQxw1UN8bEZrcE3gEPi7DCWauIYqAybDC47vZdeKWJp96DvO5Nh0e8+WcgFCxwcerD83VlxL5AOTXVRYIp47ViLGIs+dM2hX+kpjaADk/T5kLHQU9vX+plQ1Rz4uAS3dmFMgsl2VFSWmyLNVG0IjgKjtDWO2ntGfDMZddmCq6l/NOA0yhKJDYSho00SieZf+w5SYO3lDTXC1qJmACps3 raute
- name: sush
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmB85v4PUwEDddSsGo85NWvxfyTdhlaJzxSXXaL+g1N488PgakbJ0NSz3oZqNMYkWDm8sQKznZ0I+WF1CURTPucVpQr5o0H8iW0HpnXJ7wyI263rPqshGwmu3TWOL5JanVi+TnNR19+gfKTXKRTVo5BzVWRVO61T6+TLQ5+pKY+DBJiMZEZ2fM3cUfqi3A5sT5PRqdcWSR17wGrocyobmu6cHA9J+c1FlRAXTyWRV1/UmVbHIt7nMvLqIsPh4KtHu8q/Y5ibhgBzIO2+96Dex/EpCXVAm0enXZM4vXb+Ms+RiB28FLMK5tcQlLCIRrdh1tgYGIE1+Ar/8UD8Wa5IWDak92EJ7XU42C3KeQ1gmQB07uTtVuxwoXxEMjM726BkSgkz4uFwQYgitnbykd/GGitDa/BM28I3JGy5PpbzQoFFmiEKWMhDpkTLmWW6gP6LK07YAyFTpOZvDMAthhEPZorvH1JUQ1D5aGL5UiPxwn4gQXuSgE5FlhAigWi4KrjtEh+o2YUQezMQ8uvg2duc5p6Kbr+b680Q+k/XnruAdAMVkOTdcZr/JXgva4tFRHdc3w8BFZQMMuvOeclHzqvXDd2lEa17zFBMsfJa30ZpDP3ejuyspEseE0NlLlnrwAHbQLp24IaPK0nsLYeCIyOXdcKfV/mooDuRBO8Qde9zhghQ== sush
- name: bschelm
  key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkXM+2nsondT0uo/oZrgj3cPjaVCXTkAowaUHOD65qPJlFyPm9S+GBeVquyOOXK0Sj3PGn0w8/Jug0eAlFX7jiGfywcluq9doddCxDEDBkvDmZpTVNh9aQsBhUgJzolRzCZQT1wJJXA3Gz5yNp0dBjwd+n86TWV2Lv9zYQcZpKZEWQl/p5ILiCDSGjBhKlV/Z6ToWQc4uFj150wzA8fXpqZ4Z3UMIPQwSGdd9xNe2s3h8jXT/0bJBEgpR5PaCQF5rwoirdBgJ36WDW2mzXHBNFrZB9ZdOh/c2don6809vveCdKrkmoJtQnAVL+BPjp5Kat/7fggRcIAJrAp0V9jwSOw== bschelm
- name: tobby
  key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDQdNksKF6eBwhGItbjTOBKYqHx0nbjeLxu1iDfvZ4iK tobby
- name: mrplow
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5D6EhJy78IVtoFEK1+bPUi20jP5IiP5ivCaZt1i8Mx4gDT4lgRYHoWvxvghUlh0eHsGb8qEGfp9t9iFhiKaDkA+0OMZf5znLmUPZi5uwfbastj6NjkmP/kd9oXa356U7BY35gTm6P8s6FcKErGXiBihdhEygu/7ehP88jBgsJPQM71Y/YJsyeyXXwne/O1TQrwszHRDnK6G+wW0mQloFY1n4N35o/1PpjPd6l/zZfQmXoLWtv4eCgX15cssuHqB1KhXbenvVzrHWuhmPUBqXYZQB5CPyos1RyXFuT7uAn7+L0QGY69StJ4oDAlU1t8PCF1fpbCYyC7yL+U5UPHmk6cLQZZyRHrKnWpzrr7FNdtnch1XEPt300qY0lG8pk+3+Zde0LZVbevCpgReUxmcwbqQPaNcGWaQEpk9rtbtuH94aio7MCpqfQy9QU+qWAv0YihRZ9mZG1QqmZIY3wFrKJun4AtSylxrB2GWTl0sAS6yCFZku6oSFfo6nL9rNmPbjFYo0a25leDmd9dV2rFr8Qc24J4Ij6OhX1MxYIdroSOX+DiwaFw2xSTmcQKZFqFiPOsY2GBDGakXpLAgvmWEyYbpsmAd3mbRpk+zxC0dC+powehOT7NlVOryjHOBb3LsMiRHCbQ0C5n4KZPxi+XfcOVxmvJgxfJFOmKCVXWZE5bw== mrplow
- name: leon
  key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAigKfQI2+hpITSVCqnz/UcQyldjE6Qjud3GvQfkr7sfG1PqdVpsh0UogWjsejWDwpdi4IIgGyrk9rlLdvFFl10V474T2/dgKrpD6+tyZ0GLgP8LFMlH/cX7Y+TVLNm0HiLSFp9pd2T0pAneKP7eDxKn9E6MvFMTMcULkQGwLBxrkdLaPYzVKkUV7/Jh0Yi91CzMIR3IPK9/Y0ZDbhocdLv5ROztHki0MnWu/E/VIDZZkFmNdCo2IkuyYX3Gg1WIb8aEsa00+PFjIuYbwz8+QssogWHMHeWcCG2uEWqxbNiREMLiLRCcS/ItGQ9RddF209rgSMPNyJg9EwZ/hRv6utCdaSn8Bu+mTQFeTWxSw/9RACx3PanHXIUhgfGcC3Flsrb7hfTDzmVZa3pq/1+suwQdVkZ32t4ZWg43QiaO1ER/m7LOvBWtIKBEYX/fygv7gepfv1eKBFTAIWm+0dwGIR1J8R8S+m1pZCb2U/bZxXKAk4XGfmwurXaRu9Ca3UYWBh37dcaZQrvz+LuDrMwb4MWjLLvai81MoNpmLMYVOa8Djk/gvojL6iP1covUUI2MVF1PrSna/JJ5QfDz1ZDNcnW7AS06xm2FuyigY2MCgwKKSX1yfIeqy8tZR9xyJdLoLCa4D8/b2ifY39VtmJ04BlFfUTeI3i0jn/dXnfSn6UWmU= leon
- name: codefetch
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDM8uhJ9Qin1Bnt1gVkhQEocIK+ziP4Ht0uCP1QPaTPza8hXxLrf5pizAxWpjM7Jnr3UFc/IpOMUII7B67MPlcUvlryQGESNQqGUDEoDbTww1wh79G86x4Q7xMS1q35H6E9KX0WUGMhdcHCOn4XQbIeNB6BY1NL27JgNE4I84oMhWbDdUnR36ZPCWvkm+7PKr92MacCZU/z7lBRHcW0zfCug4YuO3vOqtv1UQl3z2dsgK1VkyuDxyNXSeRufKyJJveqURzx1A5wZVQ3Qc7nIj00yx3GVsYMZH3oX6PuPiu+fu4nzvwiiWaqf/PFqa9Rfof1hQJy29Be8ggfbKZwEF4dCBGhydTF66hm729OzWry7XN49aZAmjHEe84ivDL16SjQjGWPFygMQdpQSovIT8t0vzfuNKRElhMEBAM4BxvLiWtaKFOhxXhMlK7rTmGBzouarFcR5ka1OFYD36z1rv8REEviUMv1QbFtIx1TD3HrliNt18lJE5d5AyDxadWy6Lf7WlPpVZnxydTneyE7UwtSt9vwx2zdNEOG6ygxOjY9JbiO12/kkyLeTyMq7+o0uY5oV2xo+I3aVYVS0jv3VHrTqtb/1nDWTb7Y9TTe8b0nOZOkOnnzOxWBvSms7MOh0NOA2I3ZpkIhKcWqdCvyKFfeUaita4sYKOrIwelYhyGQmQ== codefetch
- name: DarkAMD
  key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAhx0r/mvxf4YZd+cK/JAQJyNo2fubv7K60UAWWFG8sCIAzg1U8ORoidAJax16nmNpe4iXeyrzXDHoLWHfANKOzlf4peDwaZWOHHlfUQ6kV2S10ndHJOQ4isFj+hT7qU50vWknV2IdCwgRPjL5kMU8R1Kux7b9kJz41VPocJcZNQbqQsvuTUrsFSCHw2nZvglX5tScyNIyU9EC1Ee0LY9KCA4STx84WHyAoGN7m/D1XtPEczIJXuRzmDWErqPXV0sZXoMJ860anUZqRZSXTumH6Z20nzGWD4iYX5kuuDPba4cuOmtHisDyGVhle2xnI/qUAF5u2abYRlBI6DHWXWnNmw== DarkAMD
- name: s_2
  key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8M75KrippHPwkAJYrc+GKRAttD1x9ZgZEZSF9UZ/Tk s_2
- name: ctandi
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6f4GU51qSPSDM98KB7joDAzWXf7jbbZi9a7KfTsYBaT1nqlcCsltPBTKUa6cjgUYVrDL3QnKA8nsa24ZSROZA4X9b1TUBNKhdR6CldoOtr+QRjEfmRJ+qDrDJD9yjX//9D4sKmhGZ7JX/5xTGgqUW9OlMudvxOXof11KDeJk+X4jmvUmsQS+GF5+YOg7UI+2vsxbDJK9kgkryzWRl7+7uSmd4e3UJn+P2NeHf85JReZnelYyWzqDRykc0IuwtuvHvgDMOo1xArveWC/dmGJ/HGWti0JJ5SJSOsaSVD4tEA7Cyp8lmeEYE2JmGrC07izLglc/YrCB/UdEbMkY/5st7 ctandi
- name: awx
  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI/IcNE1nswKJaKIQ3EWNeC/MUXxE6JESTmy2VIAXR26exqqyK0P5vN+JXLE9Xb6VXkjrIEQNrRgAXcVsB/V57tTX/tECMCsIDshU5vYVJZuTk1ThA2mThTdFadejT0Dnh0XTxSlWKdSwQtqw8Z9p0jST1zBDiqEFo7LRyDZWBJngoMTEYvfJOfuObxhuFoo26IAAGE0y+2VN9AXllLLAzEI98RaYE9fZkBNQ4lP4bwvGBsAMCEQuZPRjqS+b/yccuBcDcgTRoB323uSoR3D3AT/vI4vXFzD+xCjcPUCoEbiVn/zgp7Kau2NjGRN8kQt7kuCzp9ea+y9fVzaHO466yjPEQtIZJ6gkmn2rfSpNXKk7acrDs+mehddNRlH/jQvTh7+4+/6fuYs2BhQH2tF/VGaIkQkmursi6GaCfY2NrjG2z834O/Zn9NCjpk1/RQ+k5JqG5yqEYfAJopeqpS7kct5T3NsRNvLEuGFvnu0IpioEEan9OPhzdcVC6wIs9Ph8= ffh awx key
admin_authorized: [lemoer, cawi, aiyion, jue, okrueger, raute, tobby, sush, codefetch, DarkAMD, ctandi, s_2, beschelm, awx]
dns_recursive_allowed_private_rdns_zones:
- "8.0.0.0.e.e.f.f.a.c.d.f.ip6.arpa."
stats_address: "{{ lookup('dig', 'stats.ffh.zone.') }}"
babeld_build_version: "babeld-1.9.1"
zabbix_agent_server: "{{ lookup('dig', 'zabbix.ffh.zone./AAAA') }},{{ lookup('dig', 'zabbix.ffh.zone./A') }}"
zabbix_agent_server_active: "{{ lookup('dig', 'zabbix.ffh.zone./AAAA') }},{{ lookup('dig', 'zabbix.ffh.zone./A') }}"
domains:
- id: "10"
- id: "11"
- id: "12"
- id: "13"
- id: "14"
- id: "15"
- id: "16"
- id: "17"
- id: "18"
- id: "19"
- id: "20"
- id: "21"
- id: "22"
- id: "23"
- id: "99"
domains_with_dom0:
- id: "0"
- id: "10"
- id: "11"
- id: "12"
- id: "13"
- id: "14"
- id: "15"
- id: "16"
- id: "17"
- id: "18"
- id: "19"
- id: "20"
- id: "21"
- id: "22"
- id: "23"
- id: "99"
apinger_targets:
- description: sn01
  ips:
  - 10.10.10.1
  - 185.197.132.140
  - fdca:ffee:8:18::1001
- description: sn09 
  ips:
  - 10.10.90.1
  - 81.3.6.92
  - fdca:ffee:8:18::9001
- description: sn10
  ips:
  - 10.10.100.1
  - 81.3.6.91
  - fdca:ffee:8:18::a001
- description: google dns
  ips:
  - 8.8.8.8
- description: heise.de
  ips:
  - 193.99.144.80
  - "2a02:2e0:3fe:1001:302::"
# defaults
is_supernode: false
is_exitnode: false
is_superexitnode: false
