---

servername: sn06
sn: 6
en: 6
fqdn: "sn06.s.ffh.zone"

exit_ip: "45.12.203.129" # With this, we do SNAT in favor of MASQUERADE
mesh_prefix: "2a0a:4587:2032"

mesh_fastd_firewall_open: true

apt_codename: "trixie"

legacy_dom0: true
radv_announce_default: true
fix_netifnames: false
no_babel: true
iperf3_is_public_server: true

zabbix_agent_server: "zbx-ham.ffh.zone"
zabbix_agent_server_active: "zbx-ham.ffh.zone"
