---

servername: sn06
sn: 6
en: 6
fqdn: "sn06.s.ffh.zone"

exit_ip: "45.12.203.129" # With this, we do SNAT in favor of MASQUERADE
mesh_prefix: "2a0a:4587:2032"

mesh_fastd_firewall_open: true

legacy_dom0: true
radv_announce_default: true
fix_netifnames: false
no_babel: true
iperf3_is_public_server: true

zabbix_agent_server: "zbx-ham.ffh.zone"
zabbix_agent_server_active: "zbx-ham.ffh.zone"
zabbix_agent_psk_id: "sn06.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35616639656163313732313132333466333063363534356532633865356637636239313064613165
          6161353534383938383363613437643465346539306239650a363138613236333330306331616437
          32656535643136643365653161303331373462396236383032636166636663626130636438303834
          6539326261333931390a373036383265356234643064626265333265633633393936333033313763
          34643066373833633432643337616163356133623366386137303166666334643561373130333034
          36326434356464363765346464303738636437343666366263393239323735303830346461373332
          65616435346536633963313035613539363133346432383564363132386136333336396133373632
          34313662333931366661
