---

servername: fra-client
fqdn: "fra-client.ffh.zone"

zabbix_agent_server: "zbx-fra.ffh.zone"
zabbix_agent_server_active: "zbx-fra.ffh.zone"
zabbix_agent_psk_id: "fra-client.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30386233383766633835306262643930623364643038373761623866343231373730343839363364
          6363396334643331633764346661663837623839316134620a313139323065303230643038386634
          61363633323238363333633832386132353562383563313932633331306534346130383034636236
          3334636639343365370a336637383864313262323939313631656130356135666632383433646430
          63373765343938316232346264653961656335663134373063666236366265633961356162353735
          32663530633838323738646638313861323064663135333063653534373831336363383061333862
          37316430656531343235396539386264623939333136613730353861313866623361663236346163
          61633662353839373366

restic_backup_paths:
- "/etc/"
restic_backup_excludes: []
