#SPDX-License-Identifier: MIT-0
---

keepitup_path: "/opt/keepitup"
keepitup_user: "keepitup"
keepitup_group: "keepitup"

keepitup_fqdn: "https://keepitup.example.com/"
keepitup_nodes_url: "https://harvester.example.com/api/nodes.json"
keepitup_map_url: "https://www.example.com/karte/#!/de/map/{node.nodeid}"
keepitup_stat_url: "https://stats.ffh.zone/d/EGysRPsMz/router-fur-meshviewer?orgId=1&from=now-7d&to=now-1m&var-node={node.nodeid}"
keepitup_flash_secret: "secret"
keepitup_debug: false

keepitup_smtp_host: "smtp.example.com"
keepitup_smtp_port: 587
keepitup_smtp_replyto: "service@example.com"
keepitup_smtp_from: "keepitup@example.com"
keepitup_smtp_starttls: true
keepitup_smtp_user: "some_login"
keepitup_smtp_pass: "secret"
