---

servername: dns4
fqdn: "dns4.ffh.zone"

networkd_configures:
- iface: lo
  addresses:
    - 127.0.0.1/24
    - ::1/128
  no_radv_accept: true
- iface: ens16 # mellanox
  addresses:
    - 81.3.6.93/29
  gateway4: 81.3.6.89
  dns_server:
    - '2001:678:ed0:f000::'
    - 5.1.66.255
    - 9.9.9.9
  no_radv_accept: true
- iface: ens18
  addresses:
    - 192.168.152.2/24
  no_radv_accept: true
- iface: ens19
  addresses:
    - 2a0a:4587:2033:10ca::53/64
  gateway6: 2a0a:4587:2033:10ca::1
  no_radv_accept: true

nftables_enabled: true
ferm_enabled: false

knot_interfaces:
  - 2a0a:4587:2033:10ca::53@53
  - 81.3.6.93@53
knot_secondary_dns: true

restic_backup_paths:
- /etc/
- /var/tmp/zabbix_proxy.db

zabbix_agent_server: "zbx-haj.ffh.zone"
zabbix_agent_server_active: "zbx-haj.ffh.zone"
zabbix_agent_psk_id: "dns4.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63353133653164656636633238383664336263613434633963663436373130346462373362343034
          3766626232646137656366376638626535656462636262350a306162643463373833633166313666
          62326636653032383366326235306365666564303431393764383163393135383264376534323038
          3733636263653831350a396534623864633937313336356631616330613963303863366335386337
          66313735343938663164396166636664336164646264326232363963353466613130663562643237
          35303935393737646465663630633134376333376364393730373764346237373236346437653038
          32356364383632316162663731376564396231646365346465656535633730313261663534303833
          66626238353334646661
zabbix_proxy_hostname: "zbx-haj.ffh.zone"
zabbix_proxy_dbname: "/var/tmp/zabbix_proxy.db"
zabbix_proxy_psk_id: "zbx-haj.ffh.zone"
zabbix_proxy_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31363732343936346465363638333065353635313035613231353734306565376239326234666131
          6161663037663762323862383834373433396337663732310a373735616531303261633661363865
          35656663626462646438393736353939386132653431616561313239636431303761636238303763
          3638363039643230360a383638356137613431333264623661306634373964636136633639666132
          61633536306538366637396465656332316334303531306131626366646361616163346637636436
          66356239316238353332626534343932353963616239633636366265343433303031656639363965
          66363035613238646437626139663831633338666362366263316362373961616233383939633131
          31373034646661353834
