---

- name: Install Foswiki dependencies
  apt: name={{ item }}
  with_items:
    - tar
    - unzip
    - perl
    - libalgorithm-diff-perl
    - libauthen-sasl-perl
    - libcgi-pm-perl
    - libcgi-session-perl
    - libcrypt-passwdmd5-perl
    - libdigest-sha-perl
    - libemail-mime-perl
    - libencode-perl
    - liberror-perl
    - libfile-copy-recursive-perl
    - libhtml-parser-perl
    - libhtml-tree-perl
    - libio-socket-ip-perl
    - libio-socket-ssl-perl
    - libjson-perl
    - liblocale-maketext-lexicon-perl
    - liblocale-msgfmt-perl
    - libwww-perl
    - liblwp-protocol-https-perl
    - liburi-perl
    - libversion-perl
    - libarchive-zip-perl
    - libcrypt-eksblowfish-perl
    - libcrypt-smime-perl
    - libconvert-pem-perl
    - libcrypt-x509-perl
    - libfcgi-perl
    - libfcgi-procmanager-perl
    - libberkeleydb-perl
    - libsereal-perl
    - libtime-parsedate-perl
    - libxml-parser-perl
    - libtext-unidecode-perl
    - libimage-magick-perl
    - libcache-cache-perl
    - libxml-feed-perl

- name: Prepare Foswiki directory
  file:
    path: /var/www/web/wiki
    state: directory
    mode: 0755

- name: Check if Foswiki is already there
  stat:
    path: /var/www/web/wiki/lib/LocalSite.cfg
  register: foswiki_st

- name: Install Foswiki package
  unarchive:
    src: https://github.com/foswiki/distro/releases/download/FoswikiRelease02x01x04/Foswiki-2.1.4.tgz
    dest: /var/www/web/wiki
    remote_src: True
    extra_opts: ['--strip-components=1']
    owner: www-data
    group: www-data
  when: not foswiki_st.stat.exists

- name: Install systemd foswiki unit file
  notify: Restart FCGI
  template:
    src: foswiki.service.j2
    dest: /etc/systemd/system/foswiki.service

- name: Enable systemd foswiki service
  service:
    name: foswiki
    enabled: yes
    state: started

