---
servername: wildberger
fqdn: "wildberger.ffh.zone"

admin_authorized_local: [ wildberger ]

restic_backup_paths:
- /etc/

zabbix_agent_server: "zbx-haj.ffh.zone"
zabbix_agent_server_active: "zbx-haj.ffh.zone"
zabbix_agent_psk_id: "wildberger.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30376633313933663365646435393637656438316135376535393938316236383165613233303436
          3064623765656132393162646466323438666437663563630a373436646630316432383964636565
          34303131623966656338303663663465386330313461643661396364306166643337326565346132
          6435643761666337370a373934353661653438306230303138393363626339663137386465636631
          31643930373865636337663764383562386239306166613437656535383435363564613339316131
          62313662643230316238396133623064353132613732333631313931373864663139333333343432
          38353332386331393530656662383335366262663138623465653335396661316230306164303863
          33316266386264366534
