---
servername: wissing
fqdn: "wissing.ffh.zone"

admin_authorized_local: [ wissing ]

restic_backup_paths:
- /etc/

zabbix_agent_server: "zbx-fra.ffh.zone"
zabbix_agent_server_active: "zbx-fra.ffh.zone"
zabbix_agent_psk_id: "wissing.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333732386133396361343731626533663635616239346336336231366164643631366132376164
          3765323837396232336630613662656632376663643739660a306364313037663436353765373061
          38363531363563303563303932616363626561336632633833323433626566633035386634376664
          3435623563306463320a646233633866343939323930366263373138313636343361656565373962
          33383234646338353733373137316635663332373233333030373936656634396331626163656631
          30343364656266313638646164353037356135626466616530366132646437373562363836396565
          35396265346339663238653735646433636666333330656462666434653131363361633663656635
          37313039396330353032
