---
servername: dobrindt
fqdn: "dobrindt.ffh.zone"

admin_authorized_local: [ dobrindt ]

restic_backup_paths:
- /etc/

zabbix_agent_server: "zbx-ber.ffh.zone"
zabbix_agent_server_active: "zbx-ber.ffh.zone"
zabbix_agent_psk_id: "dobrindt.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66303639643632633239303730343834363063313730356135306534313965656166393538383538
          3838356130376430393963336531303632366666366433660a343935353065633862336637613033
          61636437376562313566393238636633333631313534306463653561346266663065373363306239
          6230343838613339330a643835376165656638363265643362303434653732633433346261653132
          38333965653536633831386334363664303236356633646364326636326364316232333630313732
          64386632343435363765393066633766396634393830313732643465363936616331663961336531
          35393465313031386165623136386365353035386566306136396130306361383532306433323830
          66623237336537663532
