#SPDX-License-Identifier: MIT-0
---

- name: reload nftables
  ansible.builtin.systemd_service:
    name: "nftables"
    state: "restarted"
  when: nftables_enabled is defined and nftables_enabled is true
