---
servername: sn08
sn: 8
en: 8
fqdn: "sn08.s.ffh.zone"

mesh_prefix: "2a0a:4587:2030"

# With this, we do SNAT in favor of MASQUERADE
exit_ip: 45.12.203.11

mesh_fastd_firewall_open: true

legacy_dom0: true
radv_announce_default: true
fix_netifnames: false
no_babel: true
iperf3_is_public_server: true

zabbix_agent_server: "zbx-ber.ffh.zone"
zabbix_agent_server_active: "zbx-ber.ffh.zone"
zabbix_agent_psk_id: "sn08.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63626638303933333435376331623430336135313366343864643130326335303264393034313630
          6533393631646266313036313131306432303636393665610a323739616437363830386330613436
          62353765396630653864323964616433386234623534313762613436363562343564396564376430
          3533393337396530650a306130613764313162373232373538356462616266666139333030326631
          62346434663066306166336466626166366362623566633136336331313834636433383430333962
          39363930333265393930393338363763616237336464643633363836313236646233653831343730
          62373937613739343034666630613630653563353030323631303231386631373233653463396264
          32626237376463336537
