---

servername: sn07
sn: 7
en: 7
fqdn: "sn07.s.ffh.zone"

exit_ip: "45.12.203.65" # With this, we do SNAT in favor of MASQUERADE
mesh_prefix: "2a0a:4587:2031"

mesh_fastd_firewall_open: true

legacy_dom0: true
radv_announce_default: true
fix_netifnames: false
no_babel: true
iperf3_is_public_server: true

zabbix_agent_server: "zbx-fra.ffh.zone"
zabbix_agent_server_active: "zbx-fra.ffh.zone"
zabbix_agent_psk_id: "sn07.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376338306235356337363364613532623435373665623737383766356239643264313537323762
          6262666631336239333662353563393836353138383362310a346362326636623262356634653938
          65356232653764323366373061626531633964336237343832653737366430376438626565656362
          3130623639626634620a313433666364646364633134353234626634333839383836646465353161
          37333132663664633235623432373632326339626162623735343663616234343163633131363637
          65626632633733656362626666383234353730336564336134386563303734313838623962653563
          39383238366436316630303466353333643739386438363237666434376564383432393835306439
          31346231383762663563
