---

servername: ham-client
fqdn: "ham-client.ffh.zone"

zabbix_agent_server: "zbx-ham.ffh.zone"
zabbix_agent_server_active: "zbx-ham.ffh.zone"
zabbix_agent_psk_id: "ham-client.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63326362623137316338336263623366643464313730653338376239643730343331393735353161
          3635313936613634333433663239363538336331653037350a383861326333626230346537386461
          63353039666664393532323266346333613730306236663138343433666662396363326539303235
          6464373862373666620a656431653534343833633966643865393365353932316639653139393261
          65346136613630663664336431383236613439643734613934633136666139393765323366656335
          65396261363061356534653366383662326161306431376366316337616538376631386537303235
          32396432326164396336376632633538393366633933306434633238383963633865376631323766
          35313166323436313965

restic_backup_paths:
- "/etc/"
restic_backup_excludes: []
