---
servername: scheuer
fqdn: "scheuer.ffh.zone"

admin_authorized_local: [ scheuer ]

restic_backup_paths:
- /etc/

zabbix_agent_server: "zbx-ham.ffh.zone"
zabbix_agent_server_active: "zbx-ham.ffh.zone"
zabbix_agent_psk_id: "scheuer.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66363065363634323933313166386134373966343035616264393233383230613537616661633232
          6562306264383732373635353937646138643861353530310a633135323463646530303763396264
          65343433356336323230356264663834376431666539353735343436383762623061353638613937
          3139343132303530380a623864653661626231313166363934633335316266656133386330353033
          62336433366534393837393031393766636466363564383432376565663337333735363439396664
          39643930333534383262316633333732383765653835616665333437623535663262353933643732
          37393462626639646233353435383836376536626337633432656637643031613930656337303037
          37303966356536373162
