---

- name: Create iperf user
  register: createuser
  user:
    name: iperf
    shell: /sbin/nologin

- name: Generate systemd unit file for iperf
  template:
    src: iperf3.service.j2
    dest: /etc/systemd/system/iperf3.service
  register: iperf_service_file

- name: Install iperf3
  apt: name=iperf3 update_cache=yes

- name: Enable iperf3 daemon on boot
  systemd:
    enabled: yes
    name: iperf3

- name: Start iperf3 daemon
  systemd:
    state: started
    name: iperf3
  register: iperf3_just_started

- name: Reload services in case service file changed
  systemd:
    daemon_reload: yes
  when: iperf_service_file.changed

- name: Restart iperf service
  systemd:
    restarted: yes
    name: iperf3
  when: iperf_service_file.changed and not iperf3_just_started.changed

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-iperf3.conf
  notify: reload ferm

- name: Restart ferm
  service: name=ferm state=restarted
  when: ferm_changed is changed



