---

keepitup_smtp_host: "mx1.ffh.zone"
keepitup_smtp_replyto: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32643831383230396565393337303237373237613430636634636333393032616563353135306635
          6265396665363761396666336137333139653231653234350a353331633763633734393832613539
          66333536326631326165393934633865626437396433616231363961343232366132333933323232
          3436623537343533610a393339643030633430653562626530386337346435313364623639623662
          61386464643430386565333539326134366139656132323431393137353232343038
keepitup_smtp_from: "keepitup@harvester.ffh.zone"
keepitup_smtp_user: "harvester-keepitup@ffh.zone"
keepitup_smtp_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62336130613930323532613962366363636330636265343766316339626165396639663530323563
          3865343631333632353338326334396633653234666364360a306366653532653834633734663738
          63346130646361323633643961373265313337333166636532373337656263306264636439313763
          3561613430663361390a333935323038316461666532323363636139333464616632326464373062
          64613932623433366663323633643633333565353164653065653930333164393130333362333433
          61303065633435623566663132626431343530643366373563613435343733613365393365343363
          30376137326334643230313962303664366638303233383864323165346137336433646433656534
          39646236383131383435
keepitup_flask_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38326261666339333362346234653439356634323737343661643632643136613463303862333130
          3039393162376633313865306261633331636638356263380a363339353439643261313033643930
          38303237316434663830356463363437353866303962633135396638393433343435653766333735
          6634373635343536340a363636383630396634656338383534623431363462646134633333613866
          63323363303162396533343861373036326339376530373831383064333734613264
keepitup_nodes_url: "https://harvester.ffh.zone/api/nodes.json"
keepitup_fqdn: "https://keepitup.ffh.zone/"
keepitup_map_url: "https://hannover.freifunk.net/karte/#!/de/map/{node.nodeid}"
keepitup_stat_url: "https://stats.ffh.zone/d/EGysRPsMz/router-fur-meshviewer?orgId=1&from=now-7d&to=now-1m&var-node={node.nodeid}"
