---

servername: ber-client
fqdn: "ber-client.ffh.zone"

zabbix_agent_server: "zbx-ber.ffh.zone"
zabbix_agent_server_active: "zbx-ber.ffh.zone"
zabbix_agent_psk_id: "ber-client.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61336462326162353562643036333034393636663837623165303336313865616239366637633664
          3233376661373864626339646237623036613562316331310a316636326335396361373336663131
          39656438656135376134363230613239303162373636323738396330306439363133373039633837
          6336376231323437370a313536663834616364393866623564613561373338663532326434333836
          65626361396264623935663764363137373639653361646231646363643833353132323733663933
          32336330646265333037633338663062333635383235663738613565393634343561653035373663
          38366562626433303835313563663761386336646465316635333762313863333031363865346432
          33366361343733383538

restic_backup_paths:
- "/etc/"
restic_backup_excludes: []
