---

- name: GRE stuff
  include_tasks: gre.yml

- name: Kernel modules stuff
  include_tasks: kmod.yml

- name: Firewall stuff
  include_tasks: ferm.yml

- name: sysctl stuff
  include_tasks: sysctl.yml

- name: Routing stuff
  include_tasks: routing.yml
