---

- name: Install ip_gre kmod on boot
  lineinfile: dest=/etc/modules line=ip_gre

- name: Install nf_conntrack kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack

- name: Install nf_conntrack_ipv4 kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack_ipv4
  when: ansible_distribution_release == 'stretch'

- name: Install nf_conntrack_ipv6 kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack_ipv6
  when: ansible_distribution_release == 'stretch'

- name: Install nf_conntrack_proto_gre kmod on boot
  lineinfile: dest=/etc/modules line=nf_conntrack_proto_gre

- name: Load nf_conntrack kmod
  modprobe: name=nf_conntrack state=present

- name: Load ip_gre kmod
  modprobe: name=ip_gre state=present

- name: Load nf_conntrack_ipv6 kmod
  modprobe: name=nf_conntrack_ipv6 state=present
  when: ansible_distribution_release == 'stretch'

- name: Load nf_conntrack_ipv4 kmod
  modprobe: name=nf_conntrack_ipv4 state=present
  when: ansible_distribution_release == 'stretch'

- name: Load nf_conntrack_proto_gre kmod
  modprobe: name=nf_conntrack_proto_gre state=present

