---

dms_version: "15.1.0"
dms_fqdn: "mx1.ffh.zone"

dms_path_base: "/media/dms"
dms_path_data: "{{ dms_path_base }}/data"
dms_path_state: "{{ dms_path_base }}/state"
dms_path_logs: "{{ dms_path_base }}/logs"
dms_path_config: "{{ dms_path_base }}/config"
dms_path_rspamd_override: "{{ dms_path_base }}/rspamd-override"

dms_postmaster_address: "postmaster@ffh.zone"
dms_tz: "Europe/Berlin"

dms_srs_enable: "1"
dms_srs_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33663237643939643734643638386631356130363634653435393365353432336166636331333566
          3130613238656631333331306161373736356261356237650a333238366431326631343162616237
          38653866383533306431323938383231333136363661373032313434633934663064643739643437
          3066343063663136350a373739306233343335626530326131333239653964396335353836376238
          36366335366332313335303636373736306638356139306131353935356563373762336234353934
          3438316464653131333931646666666637616562653430373935
