---
# handlers file for ffh.docker


- name: Daemonreload Docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart Docker
  service:
    name: docker
    state: restarted
