---

- name: Install babeld
  apt: name=babeld update_cache=yes state=present
  when: not babeld_build_from_source

- name: Uninstall babeld
  apt: name=babeld update_cache=yes state=absent
  when: babeld_build_from_source

- name: Include 'Build from source'
  include_tasks: build_from_source.yml
  when: babeld_build_from_source

- name: Install babeld supernode config
  notify: Restart babeld
  template:
    src: supernode.conf.j2
    dest: /etc/babeld.conf
  when: sn is defined

- name: Install babeld exitnode config
  notify: Restart babeld
  template:
    src: exitnode.conf.j2
    dest: /etc/babeld.conf
  when: en is defined

- name: Install babeld systemd service
  notify: Restart babeld
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/babeld.service
  when: ansible_service_mgr == 'systemd'

- name: Generate firewall config stanza (ferm)
  register: ferm_changed
  template:
    src: ferm.conf.j2
    dest: /etc/ferm/conf.d/50-babeld.conf
  notify: reload ferm

- name: install /etc/default
  notify: Restart babeld with service
  template:
    src: default.j2
    dest: /etc/default/babeld
  when: ansible_service_mgr != 'systemd'

- name: Systemd daemon-reload
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: Enable systemd service
  command: systemctl enable babeld
  when: ansible_service_mgr == 'systemd'

- name: Start systemd service
  command: systemctl start babeld
  when: ansible_service_mgr == 'systemd'

- name: Start service
  service:
    name: babeld
    state: started
    enabled: yes
  when: ansible_service_mgr != 'systemd'

- name: "Cronjob: restart babeld once per day"
  cron:
    name: "Restart babeld"
    job: "systemctl restart babeld"
    hour: "{{ sn | default(en) | default(12) }}"

