---

zabbix_server_dbhost: "db.ffh.zone"
zabbix_server_dbport: "3306"
zabbix_server_dbname: "zabbix"
zabbix_server_dbuser: "zabbix"
# zabbix_server_dbpassword: "set in vault"

zabbix_agent_server: "127.0.0.1"
zabbix_agent_server_active: "127.0.0.1"
zabbix_agent_psk_id: "vds.ffh.zone"
zabbix_agent_psk_value: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32306238343031306134623833613934393662316431343438376363623265626634333362643066
          3963366238386461366666663832613064336631323536650a616335646534336633663034613932
          33643734343132383532353531383936633238656133396263353463353933306233363436653265
          3235303766613264380a383061333065356332663632343533393733653336393062363030396163
          31636638343662323265666133303063386239383363333465343835633762343761383334653835
          36303565316562323032383138366530643539313039646230613661376131396432323837626539
          63626363316637626631636461376163373034623434363638643932353332373239333232316164
          32346664613037336230
